### ISSUE TITLE
Category pages

### ISSUE THREAD

**Issue by DanielHeath** [schollz/cowyo#101]
I'm thinking of adding 'category' pages (named eg `Category: <category name>`).

My first thought on how to implement it:

 * A category page text is one link to another page per line (order unimportant).
 * While editing a page, show a sidebar with a list of checkboxes for all categories that exist (to toggle membership in the category).

Thoughts / opinions?

**Comment by schollz** [comment]
I mostly think about using cowyo as a single page standalone - so I never thought about adding categories. I think it could be useful, but I'd rather not complicate the UI much more. Maybe it could be put in as a footbar?

**Comment by DanielHeath** [comment]
One option would be to allow a forward slash in page names; the first part being the category. 

Then automatically render the list of “child pages” at the end of the parent page.

Thanks,
Daniel Heath

**Comment by DanielHeath** [comment]
This has been merged.

**Comment by nii236** [comment]
Hey @DanielHeath can you provide some insight on how to use this feature? I can't seem to get the correct 'parameters' to get the footer to appear.

**Comment by DanielHeath** [comment]
It's been a long time, and I don't use cowyo a heap anymore, but IIRC if you have a document named `foo` and a document named `foo: bar`, the latter appears in the footer for `foo`
