### ISSUE TITLE
A separate /ls type page only for all uploaded files

### ISSUE THREAD

**Issue by twocow** [schollz/cowyo#124]
When hosting cowyo for public, admins would find such a listing page useful to moderate fishy stuff and take inappropriate content down

**Comment by schollz** [comment]
Yeah this is a good idea, the uploading is relatively new but this should be doable.

**Comment by DanielHeath** [comment]
Added `/uploads/` to my open PR

**Comment by DanielHeath** [comment]
This should now be resolved; you can go to /uploads.

**Comment by schollz** [comment]
Thanks again @DanielHeath
