### ISSUE TITLE
How does sitemap.xml work?

### ISSUE THREAD

**Issue by veganexe** [schollz/cowyo#125]
And do I need to change these domains?
[This](https://github.com/schollz/cowyo/blob/1c7524cc45113c737df25b418334379ea01eed5d/static/text/sitemap.xml#L4) and [This](https://github.com/schollz/cowyo/blob/50624e75e90504e24c918fa418c21d05a97f835f/handlers.go#L239)

**Comment by schollz** [comment]
Oh whoops! Yeah, the first one doesn't matter, that file can be removed. The second one should be changed to be the known public URL. I'll have to make a CLI flag for the public URL.

**Comment by DanielHeath** [comment]
Could you draw the public URL from the Host header sent with most requests (if none are provided on the CLI)?
