### ISSUE TITLE
How to POST using curl?

### ISSUE THREAD

**Issue by twocow** [schollz/cowyo#128]
I know there is the cowyodel repo. But it doesn't seem to work with access code set.
And I would prefer a simpler way to POST like curl which supports authorization headers. I have tried POST-ing as a Json struct, but it doesn't seem to work. Can you please help?

**Comment by schollz** [comment]
Sure, its very easy:

```
curl -H "Content-Type: application/json" -X POST -d '{"page":"testpost","new_text":"hello, world"}' https://cowyo.com/update
```

That will change the page at https://cowyo.com/testpost/edit

**Comment by twocow** [comment]
Thanks. 

How do I upload a file using curl?

**Comment by schollz** [comment]
You should just do a curl POST to `/uploads` with the file data in the form `file`.

**Comment by twocow** [comment]
I tried and I'm failing.

`curl -d "@payload.md"`

Can you please give me a working example command?

**Comment by DanielHeath** [comment]
With an access code set, you need to add `-H 'Authorization: <access-code>'` or similar I think.

**Comment by DanielHeath** [comment]
Once https://github.com/schollz/cowyo/pull/129 is merged, the login page will include (browser-invisible) instructions for curl users.

**Comment by DanielHeath** [comment]
That's merged now; you should get inline instructions if you update to the latest and try again.

**Comment by schollz** [comment]
Thanks @DanielHeath!
