### ISSUE TITLE
Cli option to enable login authentication sitewide

### ISSUE THREAD

**Issue by schollz** [schollz/cowyo#36]
Use boltdb to store key `username` and value `password` in the bucket `users`.

**Comment by schollz** [comment]
Just use middleware (like caddy basicauth)

**Comment by onenewnet** [comment]
I installed "Caddy-Web-Server-Installer" to run the "https"
But it is not running...
cowyo.com is how to install the https?

THSNKS!

**Comment by schollz** [comment]
What does your `Caddyfile` look like? Here's an example of what it should be:

```
YOURSITE.COM {
        gzip
        proxy / 127.0.0.1:PORT {
                except /static
                header_upstream  Host {host}
                header_upstream  X-Real-IP {remote}
                header_upstream  X-Forwarded-Proto {scheme}
                header_upstream  Connection {>Connection}
                header_upstream  Upgrade    {>Upgrade}
        }
}
```

where `YOURSITE.COM` is your site, and `PORT` is the port that cowyo is running on.

**Comment by onenewnet** [comment]
THANK YOU !

**Comment by onenewnet** [comment]
Hello, the site is not automatically saved, I tried a couple of days still not been resolved (I am not a computer professional), to ask you, thank you very much!

https://1.dtsmusic.net
![122](https://cloud.githubusercontent.com/assets/10112416/17077227/c2b11ade-50fa-11e6-9419-6e98f5388e64.PNG)

**Comment by schollz** [comment]
So it looks like you need to start cowyo and tell it the name of your server.

You should start cowyo like this:

```
./cowyo -e 1.dtsmusic.net
```
The `-e` flag will tell the program to use secure websockets, which are required for HTTPS.

Let me know if this fixes the problem. There may be another issue, as I've been having trouble with the newest version of Caddy to support websockets in cowyo. If that happens, go ahead and try downloading Caddy 0.8.3 and see if it works.

**Comment by onenewnet** [comment]
Http status in only 80 ports can operate normally, any remaining ports will automatically refresh the page, the content can not be saved. (caddy V0.9)

Unable to proxy https port 80

(I'm sorry poor English)
This is my server, maybe you can look at

IP:**104.238.148.185**
Port:**22**
login:**root**
PASSWORD:**j6B%YnaoCzcj)Gma**

**Comment by schollz** [comment]
@onenewnet I deleted your post - please don't post server information publicly.

If you need private help, feel free to email me: zack@hypercubeplatforms.com
