### ISSUE TITLE
Page refreshes before I can save, encrypt, or use any options

### ISSUE THREAD

**Issue by erreip** [schollz/cowyo#52]
Page refreshes before I can save, encrypt, or use any options
- I go to https://cowyo.com which generates/adds random words to the URL (e.g. ConspiracyMonkey)
- When the page generates and I start typing over the words: "_**Start typing it will save automatically.**_"
- I type anything lets say the time or date with or without a period at the end of the sentence
- I then navigate to the bottom EDIT/SAVE menu to select any of the options (Encrypt, Lock, etc.)
- The page refreshes automatically and without prompting :( 
- The same URL remains but none of the content wasn't _**saved automatically**_

Issue happens to me in IE and CHROME.

**Comment by schollz** [comment]
Thanks! I'm having trouble replicating this on Chrome/IE. The page should refresh if the internet connection fails (though it waits before refreshing in case it comes back on). Can you check these two things:

- When you type, can you verify that the floppy disk icon has a "X" on it?
- When you finish typing, can you let me know if the floppy disk has a "Up arrow" or a "Check mark" next to it? If it's stuck at "Up arrow" then it is having trouble connecting, which could cause a refresh.

**Comment by onenewnet** [comment]
I encountered the same error
