### ISSUE TITLE
Do you have plans to do a similar notepad.pw the website?

### ISSUE THREAD

**Issue by onenewnet** [schollz/cowyo#54]
Unfortunately I can not donate ......
Do you have plans to do a similar notepad.pw the website?
![22](https://cloud.githubusercontent.com/assets/10112416/16951998/fa94c3d2-4df9-11e6-95f6-e17f1da7d709.PNG)

**Comment by schollz** [comment]
Thanks! I appreciate the sentiment :)

How do you mean plans to do a similar notepad.pw webste - as in the same style or including the same features? Cowyo and notepad.pw share many same features - except cowyo doesn't support logins. For logins I actually prefer to self-host and have a auth/pass for the website, so I haven't felt the need to do it for cowyo. The styles, though, are pretty different.

**Comment by onenewnet** [comment]
Thanks for your hard creation, in addition to different styles, which have to say is pretty amazing technology.
I will continue to learn!~
