### ISSUE TITLE
Pages missing after migration

### ISSUE THREAD

**Issue by petrm** [schollz/cowyo#63]
Hi,
I tried the new version and all pages seem to be gone after migration.

I migrated with this command:
cowyo --data=data --olddata=olddata --debug m

This created a json file in the data folder about 4x bigger than the original database. It took surprisingly long time to migrate, which surprised me - there are very few pages in the wiki.

Then I started the server and there was no content.

**Comment by schollz** [comment]
Sorry I didn't put this in the README, but can you let me know that this is your migration process:

```
oldcowyo -dump olddata
cowyo --olddata olddata -data data --debug migrate
```

where `oldcowyo` is a [the version 1 release](https://github.com/schollz/cowyo/releases/tag/v1.1.2) and `cowyo` is the version 2 release.

**Comment by petrm** [comment]
Hi,
thanks for the hint - that was a fundamental point missing: export first. I assumed that the command migrates directly the database.
Different question: Is the UI to list the pages in the wiki gone?

**Comment by schollz** [comment]
Cool, let me know if that doesn't work.

Yes, the listing of pages is gone right now, but I'll add it back: https://github.com/schollz/cowyo/issues/65

**Comment by petrm** [comment]
Thanks, everything is working as expected.
