### ISSUE TITLE
Readme needs to explain how to create link

### ISSUE THREAD

**Issue by jemisa** [schollz/cowyo#66]
Unclear what is the syntax to link to another page of the wiki. So far neither WikiWords nor [[PageName]] are working.

**Comment by schollz** [comment]
[[PageName]] should work - once you reload the page while editing, or "view", it automatically modifies the link to [PageName](/PageName/view) which will link to view the other page. 

Please let me know if you find a case where it doesn't work so I can fix it!

**Comment by jemisa** [comment]
I actually tested [[Page Name]] (with a space, hence it not working). It works with [[PageName]]. Thanks
