### ISSUE TITLE
How to make public server?

### ISSUE THREAD

**Issue by capinski** [schollz/cowyo#72]
I'm not an expert on this sort of thing, and just wanted to make sure I'm doing it right. (Gift for Mother's Day).

I have a Ras Pi, can port forward, have a domain, and basic Google skills.

Instructions would be nice, but I can probably figure it out on my own. Just wanted to know if it was possible.

**Comment by schollz** [comment]
It sounds like you are just missing a web server. Download [caddy](https://caddyserver.com/) and make a file, `Caddyfile` on your computer with this:

```
yourdomain.com {
        gzip
        proxy / 127.0.0.1:8050{
                transparent
        }
}
```

Then just run `cowyo` and `caddy` so that they are always on, e.g. using

```
nohup cowyo &
nohup caddy -conf /path/to/Caddyfile &
```

Let me know if there are any particular steps you get stuck with.
