### ISSUE TITLE
Running the latest release under MacOS

### ISSUE THREAD

**Issue by Gardinero** [schollz/cowyo#76]
Hello,

sorry for the question, but I cannot find out how to handle the OSX file under "Latest Releases" (https://github.com/schollz/cowyo/releases/download/v2.4.0/cowyo_osx_amd64).

How do I run that file, as it is no archive, no dmg and not an executable...

Thanks in advance.
Regards
L

**Comment by schollz** [comment]
Hi @Gardinero , it should be an executable.

You may need to change the permissions on it to be executable, e.g. `chmod +x cowyo_osx_amd64` once you download it.

If you still have trouble let me know!
