### ISSUE TITLE
Local inline images

### ISSUE THREAD

**Issue by gitfvb** [schollz/cowyo#77]
Hi together..
Just read in the c't from cowyo, which is really great!
But I have a question: Linking images by http-path works fine. Is there a way to link local files or better: refer to images relative to the .exe path?
Thanks
Florian

**Comment by schollz** [comment]
Hm, thats kind of tricky because right now cowyo is built is a single executable with all the static files built-in. It would have to be a change to allow coywo to serve external files. 

What about doing base64 images? I've been thinking about adding that, so images can be included in the text.

**Comment by gitfvb** [comment]
Hi Zack, Thanks a lot for the quick reply. I see that it would be some kind of breaking the current simpleness. 
If it would be possible to copy&paste images into the text or drag&drop (similar to this comment field in github), it would be much better than manually linking the images. Then it could be handled through cowyo :-)

**Comment by schollz** [comment]
I like this idea, and it may be pretty easy to add. 
I found [this javascript library](https://github.com/Rovak/InlineAttachment) which should provide the basic functionality.

**Comment by DanielHeath** [comment]
Proposal:

## Server side

`POST /uploads` with a body will return `201 created` with a Location header to indicate where it went. The file will be stored in the data directory as `sha256-<SHA256(body)>.upload`.

`GET /uploads/sha256-<sha>` will read the file back (golang stdlib automatically attempts to guess content-type, so most filetypes will work alright) (danger: this lets you upload an HTML file and link someone to it, bypassing markdown whitelisting). To make this secure, GOOG etc use a different TLD for user uploads (probably doesn't help us). We can probably get away with forcing HTML to `text/plain` which will stop browsers trying to render it. 

Supply a filename `POST /uploads?filename=<filename>` when uploading to get a URL like `/uploads/sha256-<sha>/<filename>`; the last bit will be used for the content-disposition header (reflected XSS should be OK ).
