### ISSUE TITLE
Page overview

### ISSUE THREAD

**Issue by Martin-Oehler** [schollz/cowyo#78]
When accessing the server, a new page is created by default. It would be nice to have the option to instead show an overview of your pages or a specific page of your choice.

**Comment by schollz** [comment]
Hi @Martin-Oehler, this is a great suggestion.

I see two ways of going about this:
1) (Server-side) Have a login for users to "own" pages and see their pages.
2) (Client-side) Use cookies to remember previous pages and show a list of recently updated pages.

Unfortunately, I think option 1 is out of the scope of cowyo - I would look to https://write.as/ as an alternative.

However, option 2 is easy to do and I was planning on implementing it next. [It actually used to be in the previous version](https://github.com/schollz/cowyo/blob/accc3b5f622aaed0baf8a31f1d84aae9bb69f56a/routes.go#L232-L250) of cowyo. However, this option doesn't really help if you are accessing cowyo on different browsers/computers, but its a start.

**Comment by Martin-Oehler** [comment]
Hi, thanks for considering my suggestion. A feature like this would make it easier to use the wiki as a personal notebook, because you no longer have to keep track of pages. I was viewing this from a single-user perspective, so I didn't really consider other users.

Regarding 1: To limit the needed user management, you could enable users to "claim" pages with a unique key, similar to locking. Visiting the key as a page could give you a list of linked pages.
Alternatively you could add an admin mode with the ability to view all created pages. This way you only really need one user.
Both possibilities definitely increase complexity, so I understand if you don't want to take this path.
Regarding 2: This is probably the easiest method, but unfortunately not very reliable. You still have to track your pages by different means in case of losing the cookie.

**Comment by schollz** [comment]
Aw, the admin idea is another feature that used to be in the old version! I will add that back too. That way you can do something like URL/admin to view all the available pages. I use cowyo as a single user too and I think that would be handy.

**Comment by schollz** [comment]
@Martin-Oehler I'm an idiot - there is already an option to list all your pages. I guess its so non-obvious that I forgot about it myself. Just go to `/ls`.

**Comment by Martin-Oehler** [comment]
Thanks, this is exactly what I was looking for. You should consider documenting it. I guess we can close this then.
