### ISSUE TITLE
Menu closes too quickly?

### ISSUE THREAD

**Issue by AceBlade258** [schollz/cowyo#80]
Honestly not sure what the issue is here. If you hover over the page name and move the mouse down, it's hard to get down to any of the menu options before the menu closes.

I'm running in a simple container; so that may be part of it, but I doubt it:

```
FROM golang:alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git && \
    go get -u github.com/schollz/cowyo/

VOLUME /cowyodata

ENTRYPOINT exec cowyo --data /cowyodata

```
I have tried switching to Debian, in case it was an Alpine issue, but it exhibits the same symptoms.

Worth noting that I don't have this issue with the Windows release binary; does that have something to do with it?

**Comment by schollz** [comment]
Hi, I bet I know the problem. When you hover the mouse over, are you on the left side or the right side? 

The menu is fixed-width so if the title of the page is very long, like https://cowyo.com/alsdkjflkasdmclaksdlfkajsdlkfjas, then putting your mouse on the right side will make it impossible to use the menu. This is not a problem for short names, like https://cowyo.com/ai.

If this is the case, then I'll relabel this as a bug to fix!

**Comment by AceBlade258** [comment]
No, it happens no matter where you hover with the mouse.

Though I did test the page title thing: I think the menu taking up more space like that would look odd.

**Comment by schollz** [comment]
Sure I'll so that. Also what browser are you using?

**Comment by schollz** [comment]
@AceBlade258 I think I found the problem. I was messing around with the CSS awhile back and pushed changes to the bindata that I never reverted. It should be fixed now with bb56db31f7451a85b3f38afa7f80a9af688ea40d.

By the way, would you like to make a pull request to add your Dockerfile?

**Comment by AceBlade258** [comment]
That fixed it!

As for the docker file: I'd be thrilled to... once I figure out how to git... I literally just decided to start learning coding more than my BS scripting, so it may be a bit, but I totally will! (If you want to add it by copy-pasting my comment - fyi bash actually isn't needed, as it uses init now - 'cause you don't want to wait, I wouldn't be too sad.)

**Comment by schollz** [comment]
@AceBlade258 Great! I'll close this. 

Please do submit your Dockerfile if you'd like! Its a great way to learn.
