### ISSUE TITLE
Stacking 'Encrypt' and 'Self-destruct' does not function as intended

### ISSUE THREAD

**Issue by AceBlade258** [schollz/cowyo#81]
If you prime a page to self-destruct, then encrypt it, once decrypted it takes you back to the edit page. Once back on the edit page, there are many actions that can cause the page to save if they do something other than replace the text or navigate away. You wind up with the same page, but with `*This page has self-destructed. You can not return to it.*` at the top.

I think it would make more sense to redirect to view on decrypt - especially for pages that are primed to self-destruct.

**Comment by schollz** [comment]
Thanks, fixed!
