### ISSUE TITLE
User CSS file

### ISSUE THREAD

**Issue by gjaekel** [schollz/cowyo#87]
I don't find a way to add an "user defined" CSS to a CowYo using the precompiled executable.
 
Did I miss something or -- if not -- may you add support for it? Or is the "official way" to build an on, modified version from the source?

**Comment by schollz** [comment]
It's kinda tricky to manipulate it in the code. You'd have to change them in the `static/` folder and then rebuild, and make sure to override the current ones.

How about I add a feature like `-css mystyle.css` which will load your CSS file instead of the current one?

**Comment by gjaekel** [comment]
Hey, that would be great, especially for all users that would not be able to code.

I also tried to use HTML like `<span style="color:red;">blue</span>`  in the text, but this don't work.

What's the "level" of the supported MD? It's not "git MD" -- something like tables can't be used yet, right?

**Comment by schollz** [comment]
There is some sanitization that prevents some stuff. Tables are okay, but I
guess span/style is not. Relevant code:
https://github.com/shurcooL/github_flavored_markdown/blob/master/main.go#L79-L90

**Comment by schollz** [comment]
Okay now you can add a cssfile using `-css cssfile` and it will be the css for when you goto the `/read` endpoint.

**Comment by gjaekel** [comment]
please reopen:
* the read endpoint `/read` renders not the given `cssfile` but hardcoded `customer.css`.

**Comment by schollz** [comment]
@gjaekel The hardcoded filename is `custom.css` but it actually servers the CSS file that is inputted. The logic is weird because its a little hacky. Basically, a new variable ["customCSS" is set to the data in the file specified by the user](https://github.com/schollz/cowyo/blob/master/handlers.go#L56-L64), and then  [customCSS is returned when `custom.css` is requested](https://github.com/schollz/cowyo/blob/master/handlers.go#L199-L200).

**Comment by gjaekel** [comment]
I can relate it to the code and now understand your implementation and the "why" (the all-in-one-file-packing). I re-tested it and it works. My error in reasoning was that the file is evaluated once at startup only. From that, one have to restart the server after changes. Maybe this is not expected in common and should be stressed in the doc.

More thoughts: Maybe somebody also want to tweak the CSS in "Author-Mode". You may offer another option for that. 

If one should have "full controll" , then the head of this CSS might be
```
@import url("/static/css/github-markdown.css");
@import url("/static/css/menus-min.css");
@import url("/static/css/base-min.css");
@import url("/static/css/highlight.css");
```
But probably it's better to leave this done by the code and just to add an additional CSS include if the `--author-css`-Option is used.
