### ISSUE TITLE
"Read" Mode

### ISSUE THREAD

**Issue by gjaekel** [schollz/cowyo#88]
To use CowYo to as a Micro-CMS to publish some simple content to mostly others an not as private or open space, it would be useful to have a second mode that will not offer an empty page to edit in case of an *unknown* or *non-existing* destination but stay "read only". Maybe a a default page or list of existing pages should be displayed in this case. To prevent viewers from editing *existing* pages, the lock feature is sufficient.

One way to support this might be to 
* add a '--new-from-unlocked' option that offers the '$page|new' menu item and allow adding new pages from an unlocked state only.
* add a new "read" command handler named (`.../foo/read`) that renders the page like the view handler but without any menu. If an author want to change from *read* to *edit* or *view* mode, he may alter the URL.

This global operation mode may be invoced by an `--read-mode` option. In addition, a `--default-page` option would be helpful if CowYo is called without a page; this should disable the random page feature, also. Maybe a `--missing-page` option may point out a page in case of *unkonwn/non-existing* pages.

**Comment by schollz** [comment]
I like these ideas a lot!

The `-new-from-unlocked` is a very easy thing to do. From what I understand, this just means that the default page is "locked", maybe by a password set at runtime. The current behavior of a locked page is to go to the `/view`, so it would already be read only.

I like the idea of the `/read` endpoint too. Perhaps this can be tied to the new feature I implemented for publishing? Basically I added a option to "Publish" which doesn't do anything right now except add the site to the sitemap (so its actually indexed by google). But maybe Publish can also make the default route `/read` as well.

I also like `--default-page` and `--missing-page`. I'm not sure I understand `--read-mode`. Isn't that the same as `--new-from-unlocked`?

**Comment by gjaekel** [comment]
Dear Zack,
thank you for the discussion! The core idea of the *read* or *browse mode* might be to just display the content with no (direct) instruments to alter something and therefore perhaps without any menu. If you implement a `/read` endpoint, the links of the herewith rendered content should end with `/read` too, of course. Therefore, without "interception" one will "stay" in this mode. If it is leaved by using `/view` or `/edit`, the content might be altered if unlocked or unlockable by use of the password.

My idea of the `--read-mode` switch is to control what mode is entered if a request contains a page but no action/endpoint. For a private CowYo, the current view/edit might be convenient but for a public CowYo, it should be the browse mode. 

Yes, I'm also unsure if we need a separate `--new-just-unlocked` if the intention of the global *read mode* is to prevent either altering any content or creating new one. With this, creating a new page should be only possible from a page in unlocked state (which will come up in edit mode). One have to re-lock the current **and** the new page afterwards to prevent others from editing or creating new pages. 

This might be tend to be forgotten and maybe therefore it would be good that a page must be locked to be able to publish it.


I don't try out the Publish concept yet. But it sounds to be a good idea to restrict the `/read` to the published pages in addition.

**Comment by schollz** [comment]
@gjaekel That makes sense. Yeah, I can see `--read-mode` is definitely useful if someone is using this as a micro-CMS. I'll make some issues for these!

**Comment by schollz** [comment]
@gjaekel 

I've implemented these features into 2.8.

There is `-lock` mode for locking.

There is `-default-page` for specifying a default page when going to `/`. 

For every page that you "Publish" it will always default to `/read`. So if you publish your default page, then `/` will go to `/defaultpage/read`.

You can specify CSS with `-css`. This is only shown on `/read`.

I did not implement `-missing-page` because it is very hard to do because it requires separate logic for when you actually want to edit the page (since all missing pages could *also* be new pages you want to edit).

**Comment by gjaekel** [comment]
Dear Zack,
I'm exited of your support! I'll evaluate the enhancements ASAP. An I also hope that i'm welcome with a new proposal ...

**Comment by schollz** [comment]
@gjaekel Please do!

**Comment by gjaekel** [comment]
> For every page that you "Publish" it will always default to /read.

Sorry, don't work for me:
* calling `.../example/edit`, insert some text and publish.
* calling `.../example` redirects to `.../example/edit` (or to `.../example/view`, if I have switched to view before

**Comment by schollz** [comment]
Thanks. I found the problem. I was treating `/example/edit` differently than `/example/edit/`. Now it should work. You can check it out here: https://cowyo.com/test-publish

**Comment by gjaekel** [comment]
Well, but what's with embedded links? `[[foo]]` seems to be automatically expanded to `[foo](/foo/view)`. Should this have to be `[foo](/foo)`, now?

Please, see https://cowyo.com/different ...

**Comment by schollz** [comment]
Yeah, your right! I made an issue #97
