### ISSUE TITLE
"Diary" Mode

### ISSUE THREAD

**Issue by gjaekel** [schollz/cowyo#94]
Dear Zack,
what's about a *Diary* or *Blog* mode: With this, the "New Page" will not offer an _AdjectiveAnimal_, but the current ISO date. 

I would prefer `YYYYMMDD`,  but maybe this should be made optionally configurable by defining a pattern using an adequate (Go-) syntax.

**Comment by schollz** [comment]
@gjaekel This is a good idea. Please keep bringing the good ideas!

I will have to think about how to implement this one a little bit though. I could resort to something really hacky but I will think about it some to try to avoid that...

**Comment by schollz** [comment]
Got it! 684ff4e692da7ce06781b2fecb47b34fc100faf4
