### ISSUE TITLE
Make auto-save timeout configurable

### ISSUE THREAD

**Issue by gjaekel** [schollz/cowyo#96]
It's nice to have no need to perform any "save" action, but to my opinion the timeout is rather short and will tear the history function.

**Comment by schollz** [comment]
Done! Added in 63bdbb58249203d6b203d4d484529c2053675208.

`cowyo -debounce 2000` will change the auto-save to 2 seconds instead of the default of 500 ms.

**Comment by gjaekel** [comment]
Great.
